build test
Murakano/murakano-fe pull request #19
Opened 2024-06-27 14:51 UTC by grulla79

2024-06-27 15:17 UTC, grulla79 commented
https://deploy-preview-19--murak.netlify.app/auth/requests 로 변경해주시면 요청페이지 확인 가능합니다!

2024-06-27 17:22 UTC, sen2y requested changes
전반적으로 겹치는 코드와 정리되지 않은 코드가 많아 꼼꼼히 리뷰하기 다소 어려운 점이 있습니다.
특히 이전 병합건들의 코드를 잘 확인해보고, 션 코드에 가져다 쓸수있는 재사용컴포넌트들의 적용이 안되어있습니다. 지키의 인풋(모달창에들어갈), 헬퍼텍스트 constants 저장방식, 레아의 아이콘, 레아의 드롭다운 등등 팀원의코드를 이해하고 효율적으로 합치는 과정이 진행된 후 pr을 해야 추후 코드 관리에 훨씬 좋을 것 같습니다. 자체적인 코드의 중복보다, 다른 팀원과의 코드 중복이나 규칙 통일을 우선적으로 변경 부탁드릴게요! 고생많으셨습니다

2024-06-27 17:22 UTC, sen2y commented on public/hand-touch.svg
레아 코드 병합하셨다면 동일한 아이콘이 이미 저장된걸 확인하실 수 있을거에요
중복되는 코드는 빼주시면 됩니다. 
해당 파일 삭제후 레아아이콘으로 변경부탁드릴게요!

2024-06-27 17:22 UTC, sen2y commented on src/components/auth/organisms/Modal.jsx
> +    <ModalContainer>
동일한 코드가 반복되고 있습니다. 추후 효율적인 코드로 줄여주세요~

2024-06-27 17:22 UTC, sen2y commented on src/components/auth/organisms/Modal.jsx
> +            <Input
해당인풋+헬퍼텍스트 조합들에 대한 공통컴포넌트 틀 또한 지키가 구현해놓았습니다.
코드의 중복을 막기위해 공통컴포넌트를 개발한것이므로 해당부분은 반영해서 다시 업로드 부탁드릴게요!

2024-06-27 17:22 UTC, sen2y commented on src/components/auth/organisms/Modal.jsx
> +    if (value === "") return "필수 입력 값입니다";
헬퍼텍스트에 들어가는 값은 constants/helperText.js에서 별도 관리중입니다. 거기서 저장하고 불러오는 형식으로 통일시켜주세요

2024-06-27 17:22 UTC, sen2y commented on src/components/auth/organisms/RequestSection.jsx
> +            <option>진행 상태</option>
코드가 너무 반복됩니다. 정리부탁드립니다.

2024-06-28 00:42 UTC, jjikky commented
LoginForm.jsx 파일 확인해보시면서 가져다 쓸 수 있는 공통적인 부분들 체크해보시면 좋을 것 같아요!
InputBox 컴포넌트로 label과 Input 다룰 수 있고
updateState 유틸 함수도 따로 만들어 놨습니당
validate에 관한 함수들 모아놓은 파일두 있구용

상세한 리뷰는 한 번 수정 후 드리는게 좋을 것 같습니다

2024-06-28 00:45 UTC, grulla79 commented
넵! 확인했습니다

2024-06-28 19:53 UTC, grulla79 commented on public/hand-touch.svg
수정했습니다

2024-06-28 19:53 UTC, grulla79 commented on src/components/auth/organisms/Modal.jsx
> +    <ModalContainer>
넵

2024-06-28 19:53 UTC, grulla79 commented on src/components/auth/organisms/Modal.jsx
> +            <Input
수정했습니다!

2024-06-28 19:53 UTC, grulla79 commented on src/components/auth/organisms/Modal.jsx
> +    if (value === "") return "필수 입력 값입니다";
수정했습니다!

2024-06-28 19:53 UTC, grulla79 commented on src/components/auth/organisms/RequestSection.jsx
> +            <option>진행 상태</option>
이 부분 삭제했습니다!

2024-06-29 04:08 UTC, jjikky commented on src/components/common/molecules/InputBox.jsx
> +    <Box className={className}>
className 넣어주는 이유가 있나용?

2024-06-29 04:53 UTC, jjikky approved these changes
고생하셨습니당. 머지 후 보완부탁드려용

2024-06-29 05:26 UTC, sen2y commented
모달창 띄웠을때 스크롤방지랑, 단어 hover효과 적용안되어있음 , cursor:pointer 필요함  + 단어와 카테고리드롭다운 사이 간격 10px 안떨어져있어서 붙어보임. 클릭 범위 hover영역과 동일하게 변경
추후 개발에 반영 필요해보임다

고생하셨습니다~~

2024-06-29 05:26 UTC, sen2y approved these changes
고생많으셨어요 추가 보완사항은 체크부탁드릴게요!

2024-06-29 05:26 UTC, sen2y commented on src/pages/auth/requests.jsx
> +}
그 모달 띄워지고나서 뒤 페이지 스크롤이 안막혀져 있습니다 스크롤 막아주세용

2024-06-29 05:26 UTC, merged

2024-06-29 05:44 UTC, grulla79 commented on src/pages/auth/requests.jsx
> +}
넵 반영하겠습니다