모달창 및 요청페이지 수정사항 적용
Murakano/murakano-fe pull request #21
Opened 2024-06-29 06:29 UTC by grulla79

2024-06-29 06:50 UTC, sen2y requested changes
1. hover색상은 피그마와 동일하게 맞춰주세요 (전체단어목록과 내요청내역은 거의 동일하게 들고와서 참고하시면됩니다.)
2.  인풋창 내 헬퍼텍스트가 피그마와 동일하지 않습니다. 올바르게 입력해주세요로 통일하지말고
영어인 경우에는 영어만 입력가능합니다. 
한글은 한글만 입력가능합니다. 라고 유효성 틀렸을 때 나오게 해주고
영어, 한글 입력은 제출버튼 누르기 전에 입력하고 있을때 바로바로 체크되게 해주세요
그리고 필수조건 입력안하고 제출하면 그때 필수입력값입니다 뜨게 하면 될거같구요
한글이 ㅇ림 이런식으로 작성하면 제출 버튼이 활성화되지않아요.

3. 로그인 유무를 확인해서 주소창으로 접근했을때도 로그인 사용자가 아니라면 로그인페이지로 리다이렉트 보내주세요 alert메시지는 로그인이 필요한 기능입니다. 뭐 이런식으로? 우리 통일하면 될 듯해요
4. 등록요청 카드를 클릭했을때, 필수입력값은 개발용어 만 입니다.
5. 수정요청 카드를 클릭해도 등록요청모달이 뜹니다. 수정부탁드립니다.

2024-06-29 06:50 UTC, sen2y commented on src/components/auth/organisms/RequestSection.jsx
> +    background-color: #f0f0f0; // 원하는 hover 색상으로 변경
피그마 전체 단어목록대로 부탁드립니다

2024-06-29 14:15 UTC, trueS2 approved these changes

2024-06-30 12:21 UTC, sen2y approved these changes
고생하셨습니당

2024-06-30 12:24 UTC, merged