Feature/search result : 검색결과 페이지 레이아웃
Murakano/murakano-fe pull request #26
Opened 2024-06-29 16:37 UTC by trueS2

![image](https://github.com/Murakano/murakano-fe/assets/166217831/195d3446-56a0-4786-9108-a0d9461fc15b)
<img width="1490" alt="image" src="https://github.com/Murakano/murakano-fe/assets/166217831/6139f49d-ae8d-4528-95d9-0c8f5c217033">
<img width="1494" alt="image" src="https://github.com/Murakano/murakano-fe/assets/166217831/90abed20-0c20-47c6-ad2b-31fbf8af0952">
<img width="1512" alt="image" src="https://github.com/Murakano/murakano-fe/assets/166217831/824a1e74-255e-48fd-bff0-e18a72912875">

2024-06-29 16:39 UTC, trueS2 commented on src/components/search/atoms/Contributor.jsx
> +      <>
빈태그 삭제

2024-06-29 16:40 UTC, trueS2 commented on src/components/search/atoms/Contributor.jsx
> +  gap: 0px;
gap 지우기

2024-06-29 16:41 UTC, trueS2 commented on src/components/search/atoms/Contributor.jsx
> +  line-height: 19.5px;
지우기

2024-06-29 16:42 UTC, trueS2 commented on src/components/search/atoms/Contributor.jsx
> +  line-height: 19.5px;
지우기

2024-06-29 16:43 UTC, trueS2 commented on src/components/search/atoms/EditRequest.jsx
> +      <div>
div 태그 지우기

2024-06-29 16:44 UTC, trueS2 commented on src/components/search/atoms/ResultCategory.jsx
> +  border-bottom: 1px solid #CCCCCC;
#CCC 로 바꾸기

2024-06-29 16:44 UTC, trueS2 commented on src/components/search/atoms/ResultCategory.jsx
> +  gap: 0px;
gap 지우기

2024-06-29 16:47 UTC, trueS2 commented on src/components/search/atoms/ResultContentComponent.jsx
> +  opacity: 0px;
opacity 지우기

2024-06-29 16:51 UTC, trueS2 commented on src/components/search/atoms/ResultTitleComponent.jsx
> +const StyledResultTitle = styled.span`
span -> div

2024-06-29 16:52 UTC, trueS2 commented on src/components/search/atoms/SorryText.jsx
> +  margin: 136.04px 1px 0px 1px;
마지막 1px지워도 됨

2024-06-29 16:53 UTC, trueS2 commented on src/components/search/molecules/BadBox.jsx
> +  border-radius: 30px 30px 30px 30px;
30px 하나만 써도 됨

2024-06-29 16:56 UTC, trueS2 commented on src/components/search/molecules/BadBox.jsx
> +  border-bottom-width: 1px;
16, 17 합치기 -> border-bottom: 두께 스타일 색상

2024-06-29 17:01 UTC, trueS2 commented on src/components/search/molecules/ContributorEditBtn.jsx
> +  align-items: end;
문법 틀림-> flex-end

2024-06-29 17:05 UTC, trueS2 commented on src/components/search/molecules/SorryComponent.jsx
> +  margin: 0px 330px 386px; 330px;
0px 330px 386px 로 수정

2024-06-29 17:07 UTC, trueS2 commented on src/pages/search/[query].jsx
> +    <Container>
컨데이너, 헤더 없애기

2024-06-29 17:08 UTC, trueS2 commented on src/pages/search/[query].jsx
> +          <>
빈태그 없애기

2024-06-29 17:08 UTC, trueS2 commented on src/pages/search/[query].jsx
> +          <>
빈태그 지우기

2024-06-30 12:26 UTC, jjikky commented on src/pages/search/index.jsx
> +            <StyledContainer>
프래그먼트 삭제해주세용

2024-06-30 12:27 UTC, jjikky approved these changes
고생하셨습니다~

2024-06-30 12:28 UTC, sen2y requested changes
같은파일 여러개 커밋해서 좀 헷갈리는데 댓글단부분 체크하고 마저 수정해주시면 될것같아요~

2024-06-30 12:28 UTC, sen2y commented on src/components/search/molecules/SorryComponent.jsx
> +  margin: 0px 330px 386px 330px;
margin: 0px 330px 386px; 겹치는 코드 줄이는방법 한번 검색해보시면 좋을것같아요~

2024-06-30 12:28 UTC, sen2y commented on src/components/search/molecules/BadBox.jsx
>    background: #B8D5FF1A;
우선 공통색상 var(--) 로 적용부탁드리고,
border-bottom인데 transperent는 투명 이라는 색상이에요. 원하는 색상이 나오게 하려면 저기 색상을 입혀야하는거고 만약 밑에 밑줄이 필요없는거였다면 border-bottom 자체가 필요없겠죵?

2024-06-30 12:28 UTC, sen2y commented on src/components/search/molecules/ContributorEditBtn.jsx
>    margin: 10px 44.5px 246.29px 44.5px;
44.5px도 줄여주세용

2024-06-30 12:28 UTC, sen2y commented on src/components/search/molecules/BadBox.jsx
> +  border: 0px solid transparent;
0px면 테두리없는거에요!

2024-06-30 12:28 UTC, sen2y commented on src/components/search/molecules/BadBox.jsx
> +  border: 0px solid transparent;
테두리 없는게 정답이면 그냥 코드자체를 삭제해주세요

2024-06-30 12:28 UTC, sen2y commented on src/components/search/molecules/ResultBox.jsx
> +  border: 0px solid transparent;
필요없는 코드는 삭제해주세요!

2024-06-30 12:28 UTC, sen2y commented on src/components/search/molecules/ResultBox.jsx
> +  border-bottom-width: 1px;
!!

2024-06-30 15:29 UTC, trueS2 commented on src/components/search/molecules/BadBox.jsx
>    background: #B8D5FF1A;
이건 지워진 파일입니다!

2024-06-30 15:45 UTC, sen2y approved these changes
고생하셨어용오오옹~~

2024-07-01 02:12 UTC, merged