Feature/auth : 로그인 / 소셜 로그인 구현
Murakano/murakano-fe pull request #4
Opened 2024-06-21 02:29 UTC by jjikky

🔈 로컬 로그인 / 카카오 로그인 구현
🔈[ 공용 컴포넌트 ] InputBox, Input, Button
🔈헤더에 로그아웃 임시 추가
     조건부 렌더링을 위해 헤더에 유저 확인 api 달아 놓으면, 서버 없이 작업 못해서 우선 그냥 넣어뒀습니다

![image](https://github.com/Murakano/murakano-fe/assets/59151187/af7c5ec7-95ac-45a6-b181-4619d5dbc57b)

2024-06-21 02:32 UTC, trueS2 approved these changes

2024-06-21 02:57 UTC, trueS2 approved these changes

2024-06-21 03:25 UTC, sen2y requested changes
css 디자인 위주로 변경요청 드립니다~

2024-06-21 03:25 UTC, sen2y commented on next.config.mjs
저희 이거 true로 두기로 했던 것 같은데 false로 계속 하시려는걸까요?

2024-06-21 03:25 UTC, sen2y commented on src/constants/helperText.js
따로 관리하는 것 좋은 것 같아요!
아쉬운 점은, 피그마에 있는 것과 동일하지 않습니다.
전부터 부탁드렸던 부분이 이런 부분이라 말씀드리자면 피그마의 내용과 다르게 구현할 경우, 함께 논의 후 반영해주셨으면 좋겠습니다!
추가로 헬퍼텍스트에 *을 삽입하는 것 좋은 것 같고 *중복된 이메일 입니다., 대신 * 중복된 이메일 입니다., 이게 더 나은 것 같습니다. 띄어쓰기 수정 부탁드릴게요~

2024-06-21 03:25 UTC, sen2y commented on src/constants/helperText.js
PROFILE_EMPTY: '*프로필 사진을 추가해주세요.',
UPLOAD_TEXT: '*제목, 내용, 이미지을 모두 작성해주세요.',
저희 프로젝트에서 사용되지 않는 코드는 빼주시면 좋을 것 같습니다!

2024-06-21 03:25 UTC, sen2y commented on src/components/auth/organisms/LoginForm.jsx
> +        placeholder='아이디'
이메일을 입력해주세요.
로 변경부탁드릴게요~

2024-06-21 03:25 UTC, sen2y commented on src/components/auth/organisms/LoginForm.jsx
> +        labelText='비밀번호'
비밀번호를 입력해주세요.

2024-06-21 03:25 UTC, sen2y commented on src/components/auth/organisms/LoginForm.jsx
> +const EyeBox = styled.div`
눈알아이콘 후버효과 추가해주세요 색상은 #767676 70% -> 100% 로 변경되는 겁니다. 회원가입 쪽 피그마 커멘트에 남겨놨습니다~

2024-06-21 03:25 UTC, sen2y commented on src/components/common/molecules/InputBox.jsx
> +  font-family: Pretendard;
폰트는 전역에 프리텐다드로 설정했기 때문에 별도로 명시 안해주셔도 됩니다!

2024-06-21 03:25 UTC, sen2y commented on src/components/common/molecules/InputBox.jsx
> +  font-family: Pretendard;
폰트 패밀리 속성은 삭제 부탁드릴게요~

2024-06-21 03:25 UTC, sen2y commented on src/components/common/molecules/InputBox.jsx
> +      <Input
인풋에 대한 스타일이 적용이 잘 안되어있는 것 같습니다. 스타일 컴포넌트로 하단에 스타일 적용부탁드립니다.
**input 내 placeholder 및 텍스트와 헬퍼텍스트 모두 font-weight는 400**이 더 좋은 것 같습니다.
또한, 피그마에서 보면 input과 실제 텍스트 사이 거리는 20px인데, 인풋 padding-left: 10px으로 잡으셨더라구요. 
우선 왼쪽만 잡게되면 우측이 길이가 길어졌을때 첫번째 사진처럼 대칭이 안맞아요. 이런경우 두번째 사진처럼 패딩을 전체적으로 잡아주는 것이 좋습니다. padding: 17.5px 20px로 변경부탁드릴게요!
<img width="675" alt="image" src="https://github.com/Murakano/murakano-fe/assets/83276834/18bbc0c2-a9c7-437f-995c-f308beb2bac4">
<img width="1240" alt="image" src="https://github.com/Murakano/murakano-fe/assets/83276834/61c4471d-9d03-4454-98f5-7e5a20956fcd">

300 구현하신거 보면 실제로는 회색으로 보이고 헬퍼텍스트도 너무 얇아 이상하네요 이렇게 개발하면서 더 나은 부분에 대해 같이 공유하고 의논하고 싶어서 부탁드렸던겁니다!! 

그리고 지금 인풋박스 클릭했을때 파란색 테두리 안보였으면 좋겠어요.


<img width="669" alt="image" src="https://github.com/Murakano/murakano-fe/assets/83276834/f79ffccf-49f8-4ca6-92a5-607044afc403">

2024-06-21 03:25 UTC, sen2y commented on src/components/auth/organisms/LoginForm.jsx
> +      <Button bgcolor='var(--primary60)' color='white'>
피그마에는 회색 border처리가 없습니다.
프롭스를 많이 넘겨줘야 할때는 스타일드컴포넌트에 전부 프롭스로 관리하는것보다는
기본<Button 을 만든걸 덮어씌워주는 형태로 구현해도 좋습니다.
const LoginBtn = styled(Button)`` 이렇게요.
저 효과때문에 로그인과 카카오로그인 모두 불필요한 회색 테두리가 쳐져있으며 글자 스타일도 동일하게 들어가있습니다.
카카오 버튼은 font-weight : 500입니다. 

프론트는 디자이너와 소통이 중요한 직업이라고 생각합니다.
피그마와 동일하게 구현하는 것 쉽지 않습니다. 하지만 필수입니다! 

전
<img width="675" alt="image" src="https://github.com/Murakano/murakano-fe/assets/83276834/5a4c8d6c-6c39-4a36-a54f-15ab6babb845">

후
아래사진처럼 구현이 변경되었으면 좋겠어요
기존 피그마에서 달라지는 설정은 : 
1. 헬퍼텍스트에 '* ' 추가
2. 인풋창 font-weight 400으로

<img width="675" alt="image" src="https://github.com/Murakano/murakano-fe/assets/83276834/0afcf018-ba1f-407d-a047-35b3e244c033">

2024-06-22 06:21 UTC, jjikky commented on next.config.mjs
변경완료!

2024-06-22 06:25 UTC, jjikky commented on src/constants/helperText.js
반영했습니당

2024-06-22 06:47 UTC, jjikky commented on src/components/common/molecules/InputBox.jsx
> +      <Input
반영 완료!

2024-06-22 09:38 UTC, trueS2 approved these changes
늦게 확인해서 죄송합니다

2024-06-22 10:52 UTC, sen2y approved these changes
고생 넘 많았어용 수고하셨습니당!!

2024-06-22 10:52 UTC, sen2y commented on src/pages/auth/login.jsx
> +  justify-content: flex-start;
center로 바꿔주세요!
![image](https://github.com/Murakano/murakano-fe/assets/83276834/b0c4380d-e27e-4285-ba70-f8a2bd4adc83)

2024-06-22 11:08 UTC, merged