Rhea
Murakano/murakano-fe pull request #8
Opened 2024-06-22 17:50 UTC by dev-Rhea

확인부탁드립니다.

2024-06-22 18:08 UTC, sen2y requested changes
댓글 피드백 반영부탁드립니다!

2024-06-22 18:08 UTC, sen2y commented on src/components/words/atoms/WordItem.jsx
> +TO-DO
나중에 TODO 만 검색해도 나오도록 하단 양식에 맞게 변경 부탁드릴게요 ~
`// TODO: 이렇게 주석을 사용합니다.`

2024-06-22 18:08 UTC, sen2y commented on src/components/words/atoms/WordItem.jsx
> +
이런 빈칸은 삭제해주세용

2024-06-22 18:08 UTC, sen2y commented on src/components/words/atoms/WordItem.jsx
> +    padding: 34px 0px 34px 0px;
상하/좌우 동일한경우
`padding: 34px 0px;`
로 작성해주시면 됩니다 :)

2024-06-22 18:08 UTC, sen2y commented on src/components/words/atoms/WordItem.jsx
> +    margin: 10px 0px 0px 0px;
마진값이 하나만 들어가면 명시적으로
margin-top: 10px
패딩의 경우 상하/좌우 동일하니 
padding: 6.5px 36px;
로 변경해주세요 !

이런코드가 많아보여 전체적으로 반영부탁드립니다!

2024-06-22 18:08 UTC, sen2y commented on src/pages/words/index.jsx
> +import WordList from "@/components/words/molecules/WordList";
미사용 임포트는 삭제해주세요!

2024-06-22 18:08 UTC, sen2y commented on src/components/words/atoms/WordItem.jsx
> +            <ListBottomLine>
보통 선이 들어간경우 선을 위한 컴포넌트를 생성하지 않고
해당하는 컴포넌트의 `border-bottom: `속성으로 밑줄이 들어갑니다. 
그러면 불필요한 코드를 줄일 수 있어요!
반영 부탁드립니다

2024-06-22 18:08 UTC, sen2y commented on src/components/words/atoms/WordItem.jsx
> +            <WordListIconDiv href="/search">
`/search` 말고 해당하는 검색결과로 넘어가야합니다
예시 : `/search/${searchTerm}`
해당 코드에서는 searchTerm에 클릭된 단어가 들어가면 되는겁니다!
반영부탁드릴게용

2024-06-22 18:08 UTC, sen2y commented on src/components/words/atoms/WordItem.jsx
> +    margin-top: 250px;
`margin: 250px auto 0;` 으로 줄일 수 있습니다.
반복되는 코드는 모두 한줄로 반영해주세요!

2024-06-22 18:08 UTC, sen2y commented on src/components/words/atoms/WordItem.jsx
> -                    <h1>DOM</h1>
css 기본값을 초기화했기때문에
h1은 그냥 텍스트입니다.
스타일태그로 스타일을 입혀주세요 
return 내에서 일반 html 태그는 사용을 지양해주세요! 변경부탁드립니닷

2024-06-22 18:08 UTC, sen2y commented on src/pages/words/index.jsx
>      <div>
의미없는 감싸기용으로는` <></>` 빈태그를 사용해주세요.
스타일 컴포넌트를 사용하고 있기때문에 빈태그를 제외한 웬만한 모든 태그는 스타일 태그로 스타일을 입히고 사용해주시면 됩니다!

2024-06-22 18:11 UTC, sen2y commented
![image](https://github.com/Murakano/murakano-fe/assets/83276834/4b09fdcf-d18e-4ddb-91d2-a6085cae6bbc)
![image](https://github.com/Murakano/murakano-fe/assets/83276834/d2c3da79-f035-4eb7-9fb9-c9c6b6673ba3)

빌드 실패 에러 떴어요!
피드백 반영이랑 빌드 에러 모두 해결하고 다시 올려주시길 바랍니다!

2024-06-27 10:24 UTC, closed without merging

2024-06-27 10:24 UTC, dev-Rhea commented
테스트